apiVersion: v1
kind: Service
metadata:
  name: cluster-ip-postgres
  labels:
    app: postgres
spec:
  type: ClusterIP
  ports:
    - name: postgres-port
      port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app: postgres