apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 2
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
          image: postgres:latest
          environment:
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "postgres"
          name: postgres
          ports:
          - containerPort: 5432
          