apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: backend-service
spec:
  type: NodePort
  ports:
    - name: http
      port: 80 #This is a serive port
      targetPort: 80 #This is the target port of the pods
      nodePort: 30001 #This port is enable on node to send the traffic
      protocol: TCP  
  selector:
      app: vote-app
      