apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: frontend-service
spec:
  type: NodePort
  ports:
    - name: http
      port: 80 #This is a serive port
      targetPort: 80 #This is the target port of the pods
      nodePort: 30002 #This port is enable on node to send the traffic
      protocol: TCP    
  selector:
      app: result-app