apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
  labels:
    app: mydeployment
    type: frontend
spec:
  template:
    metadata:
      name: worker-pod
      labels:
        app: worker-app
        type: frontend
    spec:
      containers:
        - name: worker-app
          image: nxzcint/worker-app
  replicas: 2
  selector:
    matchLabels:
      type: frontend